-- ============================================================
-- משק 22 – Order Idempotency + Atomic Creation
-- Migration: 006_order_idempotency.sql
--
-- Changes:
--   1. Add idempotency_key column to orders.
--      Partial unique index: unique among non-NULL values,
--      allowing legacy orders (NULL) alongside new ones.
--
--   2. Create create_order_atomic() Postgres function.
--      - Inserts order + order_items in a single transaction.
--      - Derives user_id from auth.uid() — never trusts caller params.
--      - On duplicate idempotency_key for same user: returns the
--        existing row instead of inserting (idempotent replay).
--      - SECURITY DEFINER with fixed search_path for safety.
--      - GRANT to authenticated role only.
-- ============================================================

-- ── 1. Add idempotency_key column ────────────────────────────────────────────

ALTER TABLE orders ADD COLUMN idempotency_key TEXT;

-- Partial unique index: enforces uniqueness only for non-NULL values.
-- NULL rows (legacy orders created before this migration) are unaffected.
CREATE UNIQUE INDEX orders_idempotency_key_uidx
  ON orders (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ── 2. Atomic order creation function ────────────────────────────────────────
--
-- Parameters:
--   p_idempotency_key    – UUID string generated by the client per checkout session
--   p_delivery_zone_id   – UUID of the delivery zone (validated by caller)
--   p_delivery_address   – JSONB snapshot of the delivery address
--   p_customer           – JSONB snapshot of customer contact details
--   p_subtotal_agorot    – Subtotal in agorot (server-calculated)
--   p_delivery_fee_agorot– Delivery fee in agorot (server-calculated)
--   p_discount_agorot    – Discount in agorot (0 for now)
--   p_total_agorot       – Grand total in agorot (server-calculated)
--   p_delivery_notes     – Optional free-text delivery note
--   p_items              – JSONB array of order line items, each with:
--                          { product_variant_id, product_snapshot,
--                            quantity, unit_price_agorot, total_price_agorot }
--
-- Returns one row:
--   out_order_id      – UUID of the created (or existing) order
--   out_order_number  – Human-readable order number (M22-XXXXXX)
--   out_is_duplicate  – TRUE if this idempotency_key was already used

CREATE OR REPLACE FUNCTION create_order_atomic(
  p_idempotency_key     TEXT,
  p_delivery_zone_id    UUID,
  p_delivery_address    JSONB,
  p_customer            JSONB,
  p_subtotal_agorot     INTEGER,
  p_delivery_fee_agorot INTEGER,
  p_discount_agorot     INTEGER,
  p_total_agorot        INTEGER,
  p_delivery_notes      TEXT,
  p_items               JSONB
)
RETURNS TABLE(
  out_order_id     UUID,
  out_order_number TEXT,
  out_is_duplicate BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id      UUID;
  v_order_id     UUID;
  v_order_number TEXT;
BEGIN
  -- ── Derive caller identity from JWT — never trust a parameter ──────────────
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'authentication required';
  END IF;

  -- ── Idempotency check ──────────────────────────────────────────────────────
  -- If the same user already submitted this key, return the existing order.
  -- No new rows are inserted; the transaction is a no-op.
  SELECT id, order_number
    INTO v_order_id, v_order_number
  FROM orders
  WHERE idempotency_key = p_idempotency_key
    AND user_id = v_user_id;

  IF FOUND THEN
    RETURN QUERY SELECT v_order_id, v_order_number, TRUE;
    RETURN;
  END IF;

  -- ── Generate unique order number ───────────────────────────────────────────
  v_order_number := generate_order_number();

  -- ── Insert order ───────────────────────────────────────────────────────────
  INSERT INTO orders (
    order_number,
    user_id,
    idempotency_key,
    delivery_zone_id,
    delivery_address_snapshot,
    customer_snapshot,
    subtotal_agorot,
    delivery_fee_agorot,
    discount_agorot,
    total_agorot,
    order_status,
    payment_status,
    delivery_notes
  ) VALUES (
    v_order_number,
    v_user_id,
    p_idempotency_key,
    p_delivery_zone_id,
    p_delivery_address,
    p_customer,
    p_subtotal_agorot,
    p_delivery_fee_agorot,
    p_discount_agorot,
    p_total_agorot,
    'pending_payment',
    'pending',
    p_delivery_notes
  )
  RETURNING id INTO v_order_id;

  -- ── Insert all line items (same transaction — all-or-nothing) ──────────────
  INSERT INTO order_items (
    order_id,
    product_variant_id,
    product_snapshot,
    quantity,
    unit_price_agorot,
    total_price_agorot
  )
  SELECT
    v_order_id,
    (item->>'product_variant_id')::UUID,
    item->'product_snapshot',
    (item->>'quantity')::INTEGER,
    (item->>'unit_price_agorot')::INTEGER,
    (item->>'total_price_agorot')::INTEGER
  FROM jsonb_array_elements(p_items) AS item;

  RETURN QUERY SELECT v_order_id, v_order_number, FALSE;
END;
$$;

-- ── Grant execute to authenticated users only ─────────────────────────────────
-- Revoke from public first (Supabase default grants to public in some versions).
REVOKE EXECUTE ON FUNCTION create_order_atomic FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION create_order_atomic TO authenticated;
